// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { Authentication, Event, type Options, User } from '../sdk.gen';
import type { DeleteEventByEventIdData, DeleteEventByEventIdError, DeleteEventByEventIdResponse, DeleteEventRemoveOrganizerByEventIdData, DeleteEventRemoveOrganizerByEventIdError, DeleteEventRemoveOrganizerByEventIdResponse, GetAuthLoginHistoryData, GetEventAttendanceCountData, GetEventByEventIdAttendeesData, GetEventByEventIdAttendeesError, GetEventByEventIdAttendeesResponse, GetEventByEventIdData, GetEventByEventIdOrganizersData, GetEventData, GetEventExportByEventIdData, GetEventPastData, GetUserAttendedEventsData, GetUserData, GetUserEventsData, GetUserHostedEventsData, PatchEventByEventIdDraftData, PatchEventByEventIdDraftResponse, PatchEventByEventIdPostData, PatchEventByEventIdPostResponse, PostAuthExchangeData, PostAuthExchangeError, PostAuthExchangeResponse, PostAuthLogoutData, PostAuthLogoutError, PostAuthLogoutResponse, PostAuthRefreshData, PostAuthRefreshError, PostAuthRefreshResponse, PostEventAddOrganizerByEventIdData, PostEventAddOrganizerByEventIdError, PostEventAddOrganizerByEventIdResponse, PostEventByEventIdCheckoutByStudentIdData, PostEventByEventIdCheckoutByStudentIdError, PostEventByEventIdCheckoutByStudentIdResponse, PostEventCheckInByEventIdByQrCodeData, PostEventCheckInByEventIdByQrCodeError, PostEventCheckInByEventIdByQrCodeResponse, PostEventCheckOutByEventIdByQrCodeData, PostEventCheckOutByEventIdByQrCodeError, PostEventCheckOutByEventIdByQrCodeResponse, PostEventData, PostEventError, PostEventMassCheckOutByEventIdData, PostEventMassCheckOutByEventIdResponse, PostEventResponse, PostUserOnboardingData, PostUserOnboardingError, PostUserOnboardingResponse, PutEventByEventIdData, PutEventByEventIdError, PutEventByEventIdResponse, PutUserData, PutUserError, PutUserResponse } from '../types.gen';

/**
 * Refresh access token
 *
 * Refresh the access token using a valid refresh token
 */
export const postAuthRefreshMutation = (options?: Partial<Options<PostAuthRefreshData>>): UseMutationOptions<PostAuthRefreshResponse, AxiosError<PostAuthRefreshError>, Options<PostAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRefreshResponse, AxiosError<PostAuthRefreshError>, Options<PostAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Authentication.postAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout user
 *
 * Logout the currently authenticated user
 */
export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<PostAuthLogoutResponse, AxiosError<PostAuthLogoutError>, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLogoutResponse, AxiosError<PostAuthLogoutError>, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Authentication.postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Exchange authorization code
 *
 * Exchange authorization code for tokens
 */
export const postAuthExchangeMutation = (options?: Partial<Options<PostAuthExchangeData>>): UseMutationOptions<PostAuthExchangeResponse, AxiosError<PostAuthExchangeError>, Options<PostAuthExchangeData>> => {
    const mutationOptions: UseMutationOptions<PostAuthExchangeResponse, AxiosError<PostAuthExchangeError>, Options<PostAuthExchangeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Authentication.postAuthExchange({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getAuthLoginHistoryQueryKey = (options?: Options<GetAuthLoginHistoryData>) => createQueryKey('getAuthLoginHistory', options);

/**
 * Get login history
 *
 * Retrieve login history for the authenticated user
 */
export const getAuthLoginHistoryOptions = (options?: Options<GetAuthLoginHistoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Authentication.getAuthLoginHistory({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAuthLoginHistoryQueryKey(options)
    });
};

export const getUserQueryKey = (options?: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get user by ID
 *
 * Retrieve user information for the authenticated user
 */
export const getUserOptions = (options?: Options<GetUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await User.getUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserQueryKey(options)
    });
};

/**
 * Update user profile
 *
 * Update user profile fields such as department and program
 */
export const putUserMutation = (options?: Partial<Options<PutUserData>>): UseMutationOptions<PutUserResponse, AxiosError<PutUserError>, Options<PutUserData>> => {
    const mutationOptions: UseMutationOptions<PutUserResponse, AxiosError<PutUserError>, Options<PutUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await User.putUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Onboard user
 *
 * Complete user onboarding process
 */
export const postUserOnboardingMutation = (options?: Partial<Options<PostUserOnboardingData>>): UseMutationOptions<PostUserOnboardingResponse, AxiosError<PostUserOnboardingError>, Options<PostUserOnboardingData>> => {
    const mutationOptions: UseMutationOptions<PostUserOnboardingResponse, AxiosError<PostUserOnboardingError>, Options<PostUserOnboardingData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await User.postUserOnboarding({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserEventsQueryKey = (options?: Options<GetUserEventsData>) => createQueryKey('getUserEvents', options);

/**
 * Get user attended events
 *
 * Retrieve all events the user has attended (checked in and checked out)
 */
export const getUserEventsOptions = (options?: Options<GetUserEventsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await User.getUserEvents({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserEventsQueryKey(options)
    });
};

export const getUserAttendedEventsQueryKey = (options?: Options<GetUserAttendedEventsData>) => createQueryKey('getUserAttendedEvents', options);

/**
 * Get user attended events with details
 *
 * Retrieve all events the user has attended with event details including creator name and date/time
 */
export const getUserAttendedEventsOptions = (options?: Options<GetUserAttendedEventsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await User.getUserAttendedEvents({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserAttendedEventsQueryKey(options)
    });
};

export const getUserHostedEventsQueryKey = (options?: Options<GetUserHostedEventsData>) => createQueryKey('getUserHostedEvents', options);

/**
 * Get user hosted events
 *
 * Retrieve all events created/hosted by the user with attendee counts
 */
export const getUserHostedEventsOptions = (options?: Options<GetUserHostedEventsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await User.getUserHostedEvents({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserHostedEventsQueryKey(options)
    });
};

export const getEventQueryKey = (options?: Options<GetEventData>) => createQueryKey('getEvent', options);

/**
 * Get all events
 *
 * Retrieve all active (ongoing) events ordered by start time
 */
export const getEventOptions = (options?: Options<GetEventData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Event.getEvent({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventQueryKey(options)
    });
};

/**
 * Create event
 *
 * Create a new event (Admin/CSG only)
 */
export const postEventMutation = (options?: Partial<Options<PostEventData>>): UseMutationOptions<PostEventResponse, AxiosError<PostEventError>, Options<PostEventData>> => {
    const mutationOptions: UseMutationOptions<PostEventResponse, AxiosError<PostEventError>, Options<PostEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.postEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete event
 *
 * Delete an existing event by ID (Admin/CSG/Organizer only). Requires typing the event name on the frontend to confirm.
 */
export const deleteEventByEventIdMutation = (options?: Partial<Options<DeleteEventByEventIdData>>): UseMutationOptions<DeleteEventByEventIdResponse, AxiosError<DeleteEventByEventIdError>, Options<DeleteEventByEventIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteEventByEventIdResponse, AxiosError<DeleteEventByEventIdError>, Options<DeleteEventByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.deleteEventByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventByEventIdQueryKey = (options: Options<GetEventByEventIdData>) => createQueryKey('getEventByEventId', options);

/**
 * Get event details by ID
 *
 * Retrieve detailed information about a specific event including check-in/check-out counts and edit permissions
 */
export const getEventByEventIdOptions = (options: Options<GetEventByEventIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Event.getEventByEventId({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventByEventIdQueryKey(options)
    });
};

/**
 * Update event
 *
 * Update an existing event by ID (Admin/CSG only).
 */
export const putEventByEventIdMutation = (options?: Partial<Options<PutEventByEventIdData>>): UseMutationOptions<PutEventByEventIdResponse, AxiosError<PutEventByEventIdError>, Options<PutEventByEventIdData>> => {
    const mutationOptions: UseMutationOptions<PutEventByEventIdResponse, AxiosError<PutEventByEventIdError>, Options<PutEventByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.putEventByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Check in user
 *
 * Check in a user to an event (Admin/CSG/Organizer only). The controller expects a QR code path parameter which will be decoded to obtain the student_id.
 */
export const postEventCheckInByEventIdByQrCodeMutation = (options?: Partial<Options<PostEventCheckInByEventIdByQrCodeData>>): UseMutationOptions<PostEventCheckInByEventIdByQrCodeResponse, AxiosError<PostEventCheckInByEventIdByQrCodeError>, Options<PostEventCheckInByEventIdByQrCodeData>> => {
    const mutationOptions: UseMutationOptions<PostEventCheckInByEventIdByQrCodeResponse, AxiosError<PostEventCheckInByEventIdByQrCodeError>, Options<PostEventCheckInByEventIdByQrCodeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.postEventCheckInByEventIdByQrCode({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Check out user
 *
 * Check out a user from an event (Admin/CSG/Organizer only). The controller expects a QR code path parameter which will be decoded to obtain the student_id.
 */
export const postEventCheckOutByEventIdByQrCodeMutation = (options?: Partial<Options<PostEventCheckOutByEventIdByQrCodeData>>): UseMutationOptions<PostEventCheckOutByEventIdByQrCodeResponse, AxiosError<PostEventCheckOutByEventIdByQrCodeError>, Options<PostEventCheckOutByEventIdByQrCodeData>> => {
    const mutationOptions: UseMutationOptions<PostEventCheckOutByEventIdByQrCodeResponse, AxiosError<PostEventCheckOutByEventIdByQrCodeError>, Options<PostEventCheckOutByEventIdByQrCodeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.postEventCheckOutByEventIdByQrCode({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add organizer
 *
 * Add an organizer to an event (Admin/CSG/Organizer only)
 */
export const postEventAddOrganizerByEventIdMutation = (options?: Partial<Options<PostEventAddOrganizerByEventIdData>>): UseMutationOptions<PostEventAddOrganizerByEventIdResponse, AxiosError<PostEventAddOrganizerByEventIdError>, Options<PostEventAddOrganizerByEventIdData>> => {
    const mutationOptions: UseMutationOptions<PostEventAddOrganizerByEventIdResponse, AxiosError<PostEventAddOrganizerByEventIdError>, Options<PostEventAddOrganizerByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.postEventAddOrganizerByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove organizer
 *
 * Remove an organizer from an event (Admin/CSG/Organizer only). The event creator cannot be removed.
 */
export const deleteEventRemoveOrganizerByEventIdMutation = (options?: Partial<Options<DeleteEventRemoveOrganizerByEventIdData>>): UseMutationOptions<DeleteEventRemoveOrganizerByEventIdResponse, AxiosError<DeleteEventRemoveOrganizerByEventIdError>, Options<DeleteEventRemoveOrganizerByEventIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteEventRemoveOrganizerByEventIdResponse, AxiosError<DeleteEventRemoveOrganizerByEventIdError>, Options<DeleteEventRemoveOrganizerByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.deleteEventRemoveOrganizerByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventPastQueryKey = (options?: Options<GetEventPastData>) => createQueryKey('getEventPast', options);

/**
 * Get all past events
 *
 * Retrieve all past (completed) events ordered by start time
 */
export const getEventPastOptions = (options?: Options<GetEventPastData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Event.getEventPast({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventPastQueryKey(options)
    });
};

export const getEventByEventIdAttendeesQueryKey = (options: Options<GetEventByEventIdAttendeesData>) => createQueryKey('getEventByEventIdAttendees', options);

/**
 * Get paginated attendees by event ID
 *
 * Retrieve a paginated list of attendees for a specific event, including check-in/check-out details and pagination metadata. Supports search by name, student ID, or email.
 */
export const getEventByEventIdAttendeesOptions = (options: Options<GetEventByEventIdAttendeesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Event.getEventByEventIdAttendees({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventByEventIdAttendeesQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getEventByEventIdAttendeesInfiniteQueryKey = (options: Options<GetEventByEventIdAttendeesData>): QueryKey<Options<GetEventByEventIdAttendeesData>> => createQueryKey('getEventByEventIdAttendees', options, true);

/**
 * Get paginated attendees by event ID
 *
 * Retrieve a paginated list of attendees for a specific event, including check-in/check-out details and pagination metadata. Supports search by name, student ID, or email.
 */
export const getEventByEventIdAttendeesInfiniteOptions = (options: Options<GetEventByEventIdAttendeesData>) => {
    return infiniteQueryOptions<GetEventByEventIdAttendeesResponse, AxiosError<GetEventByEventIdAttendeesError>, InfiniteData<GetEventByEventIdAttendeesResponse>, QueryKey<Options<GetEventByEventIdAttendeesData>>, number | Pick<QueryKey<Options<GetEventByEventIdAttendeesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetEventByEventIdAttendeesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await Event.getEventByEventIdAttendees({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventByEventIdAttendeesInfiniteQueryKey(options)
    });
};

export const getEventByEventIdOrganizersQueryKey = (options: Options<GetEventByEventIdOrganizersData>) => createQueryKey('getEventByEventIdOrganizers', options);

/**
 * Get event organizers
 *
 * Retrieve the list of organizers for a specific event (Admin/CSG/Organizer only).
 */
export const getEventByEventIdOrganizersOptions = (options: Options<GetEventByEventIdOrganizersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Event.getEventByEventIdOrganizers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventByEventIdOrganizersQueryKey(options)
    });
};

export const getEventExportByEventIdQueryKey = (options: Options<GetEventExportByEventIdData>) => createQueryKey('getEventExportByEventId', options);

/**
 * Export event attendees
 *
 * Export the list of attendees for a specific event to an Excel file `xlsx` (Admin/CSG/Organizer only).
 */
export const getEventExportByEventIdOptions = (options: Options<GetEventExportByEventIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Event.getEventExportByEventId({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventExportByEventIdQueryKey(options)
    });
};

export const getEventAttendanceCountQueryKey = (options: Options<GetEventAttendanceCountData>) => createQueryKey('getEventAttendanceCount', options);

/**
 * Get event attendance count
 *
 * Returns the total number of attendees and total checked-out attendees for a specific event.
 *
 * - Requires authentication.
 * - Only accessible by users with roles: **admin** or **csg**.
 * - Organizer permission check is enforced.
 */
export const getEventAttendanceCountOptions = (options: Options<GetEventAttendanceCountData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await Event.getEventAttendanceCount({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventAttendanceCountQueryKey(options)
    });
};

/**
 * Post event
 *
 * Publish a draft event so it becomes visible to all users (Admin/CSG/Organizer only).
 */
export const patchEventByEventIdPostMutation = (options?: Partial<Options<PatchEventByEventIdPostData>>): UseMutationOptions<PatchEventByEventIdPostResponse, AxiosError<DefaultError>, Options<PatchEventByEventIdPostData>> => {
    const mutationOptions: UseMutationOptions<PatchEventByEventIdPostResponse, AxiosError<DefaultError>, Options<PatchEventByEventIdPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.patchEventByEventIdPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Save event as draft
 *
 * Unpost an event (save as draft), hiding it from regular users (Admin/CSG/Organizer only).
 */
export const patchEventByEventIdDraftMutation = (options?: Partial<Options<PatchEventByEventIdDraftData>>): UseMutationOptions<PatchEventByEventIdDraftResponse, AxiosError<DefaultError>, Options<PatchEventByEventIdDraftData>> => {
    const mutationOptions: UseMutationOptions<PatchEventByEventIdDraftResponse, AxiosError<DefaultError>, Options<PatchEventByEventIdDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.patchEventByEventIdDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Mass check-out students
 *
 * Check out one or more students from an event by their student IDs (Admin/CSG/Organizer only).
 */
export const postEventMassCheckOutByEventIdMutation = (options?: Partial<Options<PostEventMassCheckOutByEventIdData>>): UseMutationOptions<PostEventMassCheckOutByEventIdResponse, AxiosError<DefaultError>, Options<PostEventMassCheckOutByEventIdData>> => {
    const mutationOptions: UseMutationOptions<PostEventMassCheckOutByEventIdResponse, AxiosError<DefaultError>, Options<PostEventMassCheckOutByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.postEventMassCheckOutByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Check out student by student ID
 *
 * Manually check out a specific student from an event by their numeric student ID (Admin/CSG/Organizer only). No QR code is required — intended for use from the Attendance Records management table.
 */
export const postEventByEventIdCheckoutByStudentIdMutation = (options?: Partial<Options<PostEventByEventIdCheckoutByStudentIdData>>): UseMutationOptions<PostEventByEventIdCheckoutByStudentIdResponse, AxiosError<PostEventByEventIdCheckoutByStudentIdError>, Options<PostEventByEventIdCheckoutByStudentIdData>> => {
    const mutationOptions: UseMutationOptions<PostEventByEventIdCheckoutByStudentIdResponse, AxiosError<PostEventByEventIdCheckoutByStudentIdError>, Options<PostEventByEventIdCheckoutByStudentIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Event.postEventByEventIdCheckoutByStudentId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
