// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}/api/v1` | (string & {});
};

export type PostAuthRefreshData = {
  body?: {
    /**
     * Refresh token (optional if provided in Authorization header)
     */
    refresh_token?: string;
  };
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
  /**
   * Bad request - Refresh token is required
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized - Token expired or invalid
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Not Found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
  /**
   * Token refreshed successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      access_token?: string;
    };
  };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
  /**
   * Bad request
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized - Token expired or authentication error
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Not Found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
  /**
   * Logged out successfully
   */
  200: {
    /**
     * Refresh token (optional if provided in Authorization header)
     */
    refresh_token?: string;
    success?: boolean;
    message?: string;
    data?: null;
  };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthExchangeData = {
  /**
   * Error Response
   */
  body: {
    /**
     * Exchange Auth code
     */
    auth_code: string;
    /**
     * Exchange Error code
     */
    error_code: string;
  };
  path?: never;
  query?: never;
  url: '/auth/exchange';
};

export type PostAuthExchangeErrors = {
  /**
   * Bad request - Missing or invalid exchange code
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Not Found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostAuthExchangeError = PostAuthExchangeErrors[keyof PostAuthExchangeErrors];

export type PostAuthExchangeResponses = {
  /**
   * Code exchanged successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      access_token?: string;
      refresh_token?: string;
    };
  };
};

export type PostAuthExchangeResponse = PostAuthExchangeResponses[keyof PostAuthExchangeResponses];

export type GetAuthLoginHistoryData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/login-history';
};

export type GetAuthLoginHistoryErrors = {
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetAuthLoginHistoryError = GetAuthLoginHistoryErrors[keyof GetAuthLoginHistoryErrors];

export type GetAuthLoginHistoryResponses = {
  /**
   * Login history retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      login_history?: Array<{
        id?: string;
        ip_address?: string;
        browser?: string;
        os?: string;
        device?: string;
        city?: string;
        region?: string;
        country?: string;
        created_at?: string;
      }>;
    };
  };
};

export type GetAuthLoginHistoryResponse = GetAuthLoginHistoryResponses[keyof GetAuthLoginHistoryResponses];

export type GetUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user';
};

export type GetUserErrors = {
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * User not found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  /**
   * User retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      user?: {
        id?: string;
        umindanao_email?: string;
        name?: string | null;
        role?: string;
        department?: string | null;
        program?: string | null;
        profile_picture?: string | null;
        done_onboarding?: boolean;
      };
    };
  };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PutUserData = {
  body?: {
    department?: string;
    program?: string;
  };
  path?: never;
  query?: never;
  url: '/user';
};

export type PutUserErrors = {
  /**
   * Bad request - no fields to update
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PutUserError = PutUserErrors[keyof PutUserErrors];

export type PutUserResponses = {
  /**
   * User profile updated successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      user?: {
        id?: string;
        umindanao_email?: string;
        name?: string;
        department?: string;
        program?: string;
        done_onboarding?: boolean;
      };
    };
  };
};

export type PutUserResponse = PutUserResponses[keyof PutUserResponses];

export type PostUserOnboardingData = {
  body?: {
    department: string;
    program: string;
  };
  path?: never;
  query?: never;
  url: '/user/onboarding';
};

export type PostUserOnboardingErrors = {
  /**
   * Bad request - Missing fields
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * User not found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostUserOnboardingError = PostUserOnboardingErrors[keyof PostUserOnboardingErrors];

export type PostUserOnboardingResponses = {
  /**
   * User onboarded successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      access_token?: string;
      user?: {
        id?: string;
        email?: string;
        name?: string;
        department?: string;
        program?: string;
        done_onboarding?: boolean;
      };
    };
  };
};

export type PostUserOnboardingResponse = PostUserOnboardingResponses[keyof PostUserOnboardingResponses];

export type GetUserEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/events';
};

export type GetUserEventsErrors = {
  /**
   * Unauthorized - No token provided or invalid token
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * No attended events found for the user
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetUserEventsError = GetUserEventsErrors[keyof GetUserEventsErrors];

export type GetUserEventsResponses = {
  /**
   * List of attended events retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: Array<{
      id?: string;
      title?: string;
      start_time?: string;
      end_time?: string;
      check_in_at?: string;
      check_out_at?: string;
    }>;
  };
};

export type GetUserEventsResponse = GetUserEventsResponses[keyof GetUserEventsResponses];

export type GetUserAttendedEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/attended-events';
};

export type GetUserAttendedEventsErrors = {
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetUserAttendedEventsError = GetUserAttendedEventsErrors[keyof GetUserAttendedEventsErrors];

export type GetUserAttendedEventsResponses = {
  /**
   * List of attended events retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      events?: Array<{
        id?: string;
        title?: string;
        created_by?: string;
        start_time?: string;
        end_time?: string;
      }>;
    };
  };
};

export type GetUserAttendedEventsResponse = GetUserAttendedEventsResponses[keyof GetUserAttendedEventsResponses];

export type GetUserHostedEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/hosted-events';
};

export type GetUserHostedEventsErrors = {
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetUserHostedEventsError = GetUserHostedEventsErrors[keyof GetUserHostedEventsErrors];

export type GetUserHostedEventsResponses = {
  /**
   * List of hosted events retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      events?: Array<{
        id?: string;
        title?: string;
        created_by?: string;
        start_time?: string;
        end_time?: string;
        /**
         * Number of attendees (check-in count or check-out count if check-out is required)
         */
        attendees?: number;
      }>;
    };
  };
};

export type GetUserHostedEventsResponse = GetUserHostedEventsResponses[keyof GetUserHostedEventsResponses];

export type GetEventData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/event';
};

export type GetEventErrors = {
  /**
   * Unauthorized - authentication required
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * No events found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
  /**
   * Events retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: Array<{
      id?: string;
      title?: string;
      description?: string;
      department?: string;
      location?: string;
      capacity?: number | null;
      all_day?: boolean;
      start_time?: string;
      end_time?: string;
      check_out_required?: boolean;
      is_started?: boolean;
      is_draft?: boolean;
      created_by?: string;
      checkin_count?: number;
      checkout_count?: number;
      can_edit?: boolean;
    }>;
  };
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type PostEventData = {
  body: {
    /**
     * Event title
     */
    title: string;
    /**
     * Event description
     */
    description: string;
    /**
     * College/Department
     */
    department: string;
    /**
     * Event location
     */
    location: string;
    /**
     * Event capacity
     */
    capacity?: number;
    /**
     * All day event flag
     */
    all_day?: boolean;
    /**
     * Event start time (ISO 8601 format)
     */
    start_time: string;
    /**
     * Event end time (ISO 8601 format)
     */
    end_time: string;
    /**
     * Check out required flag
     */
    check_out_required?: boolean;
    /**
     * Event completion status
     */
    is_done?: boolean;
    /**
     * Custom form fields
     */
    form_fields?: Array<{
      /**
       * Form field name
       */
      field_name: string;
      /**
       * Form field type
       */
      fieldType: 'dropdown' | 'short_text' | 'long_text' | 'checkbox' | 'radio';
    }>;
  };
  path?: never;
  query?: never;
  url: '/event';
};

export type PostEventErrors = {
  /**
   * Bad request - Validation errors
   */
  400: {
    success?: boolean;
    message?: Array<{
      [key: string]: unknown;
    }>;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - Insufficient permissions
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostEventError = PostEventErrors[keyof PostEventErrors];

export type PostEventResponses = {
  /**
   * Event created successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      id?: string;
      title?: string;
      description?: string;
      department?: string;
      location?: string;
      capacity?: number | null;
      all_day?: boolean;
      start_time?: string;
      end_time?: string;
      check_out_required?: boolean;
      is_done?: boolean;
      created_by?: string;
    };
  };
};

export type PostEventResponse = PostEventResponses[keyof PostEventResponses];

export type DeleteEventByEventIdData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event to delete.
     */
    event_id: string;
  };
  query?: never;
  url: '/event/{event_id}';
};

export type DeleteEventByEventIdErrors = {
  /**
   * Bad request - Event ID is required
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized - authentication required to delete an event
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - only Admin/CSG roles can delete events
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * Event not found - the specified event ID does not exist
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type DeleteEventByEventIdError = DeleteEventByEventIdErrors[keyof DeleteEventByEventIdErrors];

export type DeleteEventByEventIdResponses = {
  /**
   * Event deleted successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: null;
  };
};

export type DeleteEventByEventIdResponse = DeleteEventByEventIdResponses[keyof DeleteEventByEventIdResponses];

export type GetEventByEventIdData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event
     */
    event_id: string;
  };
  query?: never;
  url: '/event/{event_id}';
};

export type GetEventByEventIdErrors = {
  /**
   * Bad request - Event ID is required
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized - authentication required
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Event not found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetEventByEventIdError = GetEventByEventIdErrors[keyof GetEventByEventIdErrors];

export type GetEventByEventIdResponses = {
  /**
   * Event details retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      id?: string;
      title?: string;
      description?: string;
      department?: string;
      location?: string;
      /**
       * Maximum event capacity
       */
      capacity?: number | null;
      /**
       * Whether the event is an all-day event
       */
      all_day?: boolean;
      /**
       * Event start time
       */
      start_time?: string;
      /**
       * Event end time
       */
      end_time?: string;
      /**
       * Whether check-out is required for the event
       */
      check_out_required?: boolean;
      /**
       * Whether the event is marked as completed
       */
      is_done?: boolean;
      /**
       * Whether the event is a draft (hidden from regular users)
       */
      is_draft?: boolean;
      /**
       * Number of attendees who have checked in
       */
      checkin_count?: number;
      /**
       * Number of attendees who have checked out (only if check_out_required is true)
       */
      checkout_count?: number;
      /**
       * User ID of the event creator
       */
      created_by?: string;
      /**
       * Whether the current user has permission to edit this event
       */
      can_edit?: boolean;
      /**
       * The current user's attendance information for this event
       */
      user_attendance?: {
        /**
         * When the user checked in to the event, or null if not checked in
         */
        check_in_at?: string | null;
        /**
         * When the user checked out from the event, or null if not checked out
         */
        check_out_at?: string | null;
      };
    };
  };
};

export type GetEventByEventIdResponse = GetEventByEventIdResponses[keyof GetEventByEventIdResponses];

export type PutEventByEventIdData = {
  body: {
    /**
     * Event title
     */
    title: string;
    /**
     * Event description
     */
    description: string;
    /**
     * College/Department
     */
    department: string;
    /**
     * Event location
     */
    location: string;
    /**
     * Updated Event capacity
     */
    capacity?: number;
    /**
     * All day event flag
     */
    all_day?: boolean;
    /**
     * Event start time (ISO 8601 format)
     */
    start_time: string;
    /**
     * Event end time (ISO 8601 format)
     */
    end_time: string;
    /**
     * Check out required flag
     */
    check_out_required?: boolean;
    /**
     * Event completion status
     */
    is_done?: boolean;
    /**
     * Custom form fields
     */
    form_fields?: Array<{
      /**
       * Form field name
       */
      field_name: string;
      /**
       * Form field type
       */
      fieldType: 'dropdown' | 'short_text' | 'long_text' | 'checkbox' | 'radio';
    }>;
  };
  path: {
    /**
     * The unique ID of the event to update.
     */
    event_id: string;
  };
  query?: never;
  url: '/event/{event_id}';
};

export type PutEventByEventIdErrors = {
  /**
   * Bad request - invalid or missing update fields
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized - authentication required to update an event
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - only Admin/CSG roles can update events
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * Event not found - cannot update a non-existent event
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PutEventByEventIdError = PutEventByEventIdErrors[keyof PutEventByEventIdErrors];

export type PutEventByEventIdResponses = {
  /**
   * Event updated successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      id?: string;
      title?: string;
      description?: string;
      department?: string;
      location?: string;
      capacity?: number | null;
      all_day?: boolean;
      start_time?: string;
      end_time?: string;
      check_out_required?: boolean;
      is_done?: boolean;
    };
  };
};

export type PutEventByEventIdResponse = PutEventByEventIdResponses[keyof PutEventByEventIdResponses];

export type PostEventCheckInByEventIdByQrCodeData = {
  body?: never;
  path: {
    /**
     * Event ID
     */
    event_id: string;
    /**
     * QR code token (required). The server will decode and verify it to obtain the student_id.
     */
    qr_code: string;
  };
  query?: never;
  url: '/event/check_in/{event_id}/{qr_code}';
};

export type PostEventCheckInByEventIdByQrCodeErrors = {
  /**
   * Bad request - Missing required fields
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - User has not completed onboarding
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * User or event not found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Student is already checked in to this event
   */
  409: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostEventCheckInByEventIdByQrCodeError = PostEventCheckInByEventIdByQrCodeErrors[keyof PostEventCheckInByEventIdByQrCodeErrors];

export type PostEventCheckInByEventIdByQrCodeResponses = {
  /**
   * User checked in successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      event_id?: string;
      event_name?: string;
      checked_in_at?: string;
      checked_in_by?: string;
    };
  };
};

export type PostEventCheckInByEventIdByQrCodeResponse = PostEventCheckInByEventIdByQrCodeResponses[keyof PostEventCheckInByEventIdByQrCodeResponses];

export type PostEventCheckOutByEventIdByQrCodeData = {
  body?: never;
  path: {
    /**
     * Event ID
     */
    event_id: string;
    /**
     * QR code token (required). The server will decode and verify it to obtain the student_id.
     */
    qr_code: string;
  };
  query?: never;
  url: '/event/check_out/{event_id}/{qr_code}';
};

export type PostEventCheckOutByEventIdByQrCodeErrors = {
  /**
   * Bad request - Missing required fields
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - User has not completed onboarding
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * User or event not found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Student has already checked out, or student has already checked out of this event
   */
  409: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostEventCheckOutByEventIdByQrCodeError = PostEventCheckOutByEventIdByQrCodeErrors[keyof PostEventCheckOutByEventIdByQrCodeErrors];

export type PostEventCheckOutByEventIdByQrCodeResponses = {
  /**
   * User checked out successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      event_id?: string;
      event_name?: string;
      checked_out_at?: string;
      checked_out_by?: string;
    };
  };
};

export type PostEventCheckOutByEventIdByQrCodeResponse = PostEventCheckOutByEventIdByQrCodeResponses[keyof PostEventCheckOutByEventIdByQrCodeResponses];

export type PostEventAddOrganizerByEventIdData = {
  body: {
    /**
     * umindanao email of the organizer to add
     */
    umindanao_email: string;
  };
  path: {
    /**
     * Event ID
     */
    event_id: string;
  };
  query?: never;
  url: '/event/add_organizer/{event_id}';
};

export type PostEventAddOrganizerByEventIdErrors = {
  /**
   * Bad request - Missing required fields or validation errors
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - Insufficient permissions
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * Event or user not found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type PostEventAddOrganizerByEventIdError = PostEventAddOrganizerByEventIdErrors[keyof PostEventAddOrganizerByEventIdErrors];

export type PostEventAddOrganizerByEventIdResponses = {
  /**
   * Organizer added successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      id?: string;
      user_id?: string;
      event_id?: string;
      added_by?: string;
      created_at?: string;
    };
  };
};

export type PostEventAddOrganizerByEventIdResponse = PostEventAddOrganizerByEventIdResponses[keyof PostEventAddOrganizerByEventIdResponses];

export type DeleteEventRemoveOrganizerByEventIdData = {
  body: {
    /**
     * umindanao email of the organizer to remove
     */
    umindanao_email: string;
  };
  path: {
    /**
     * Event ID
     */
    event_id: string;
  };
  query?: never;
  url: '/event/remove_organizer/{event_id}';
};

export type DeleteEventRemoveOrganizerByEventIdErrors = {
  /**
   * Bad request - Missing required fields or validation errors
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - Cannot remove event creator or insufficient permissions
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * Event, user, or organizer record not found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type DeleteEventRemoveOrganizerByEventIdError = DeleteEventRemoveOrganizerByEventIdErrors[keyof DeleteEventRemoveOrganizerByEventIdErrors];

export type DeleteEventRemoveOrganizerByEventIdResponses = {
  /**
   * Organizer removed successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: null;
  };
};

export type DeleteEventRemoveOrganizerByEventIdResponse = DeleteEventRemoveOrganizerByEventIdResponses[keyof DeleteEventRemoveOrganizerByEventIdResponses];

export type GetEventPastData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/event/past';
};

export type GetEventPastErrors = {
  /**
   * Unauthorized - authentication required
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * No events found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetEventPastError = GetEventPastErrors[keyof GetEventPastErrors];

export type GetEventPastResponses = {
  /**
   * Events retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: Array<{
      id?: string;
      title?: string;
      description?: string;
      department?: string;
      location?: string;
      capacity?: number | null;
      all_day?: boolean;
      start_time?: string;
      end_time?: string;
      check_out_required?: boolean;
      is_done?: boolean;
      created_by?: string;
      checkin_count?: number;
      checkout_count?: number;
      can_edit?: boolean;
    }>;
  };
};

export type GetEventPastResponse = GetEventPastResponses[keyof GetEventPastResponses];

export type GetEventByEventIdAttendeesData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event
     */
    event_id: string;
  };
  query?: {
    /**
     * Page number for pagination (default: 1)
     */
    page?: number;
    /**
     * Number of attendees per page (default: 10)
     */
    limit?: number;
    /**
     * Search term to filter attendees by name, student ID, or email (case-insensitive)
     */
    search?: string;
  };
  url: '/event/{event_id}/attendees';
};

export type GetEventByEventIdAttendeesErrors = {
  /**
   * Invalid request or missing parameters
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized - authentication required
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - Insufficient permissions
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * Event not found or no attendees found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetEventByEventIdAttendeesError = GetEventByEventIdAttendeesErrors[keyof GetEventByEventIdAttendeesErrors];

export type GetEventByEventIdAttendeesResponses = {
  /**
   * Attendees retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      data?: Array<{
        student?: {
          id?: string;
          user_id?: string;
          student_id?: number;
          name?: string;
          /**
           * May be null if user email not set
           */
          umindanao_email?: string | null;
          department?: string;
          program?: string;
          profile_picture?: string;
          created_at?: string;
          updated_at?: string;
          /**
           * Null if student has not checked in
           */
          check_in_at?: string | null;
          /**
           * Null if student has not checked out
           */
          check_out_at?: string | null;
          /**
           * Name of admin who checked in student
           */
          check_in_by?: string | null;
          /**
           * Name of admin who checked out student
           */
          check_out_by?: string | null;
        };
      }>;
      pagination?: {
        page?: number;
        limit?: number;
        total?: number;
        totalPages?: number;
      };
    };
  };
};

export type GetEventByEventIdAttendeesResponse = GetEventByEventIdAttendeesResponses[keyof GetEventByEventIdAttendeesResponses];

export type GetEventByEventIdOrganizersData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event
     */
    event_id: string;
  };
  query?: never;
  url: '/event/{event_id}/organizers';
};

export type GetEventByEventIdOrganizersErrors = {
  /**
   * Bad request - Event ID is required
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - Insufficient permissions
   */
  403: {
    success?: boolean;
    message?: string;
  };
  /**
   * Event not found or no organizers found
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetEventByEventIdOrganizersError = GetEventByEventIdOrganizersErrors[keyof GetEventByEventIdOrganizersErrors];

export type GetEventByEventIdOrganizersResponses = {
  /**
   * Organizers retrieved successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: Array<{
      /**
       * Student ID number
       */
      student_id?: number | null;
      /**
       * Organizer full name
       */
      name?: string;
      /**
       * Department/College
       */
      department?: string;
      /**
       * Program/Course
       */
      program?: string;
      /**
       * UMindanao email address
       */
      umindanao_email?: string;
      /**
       * Name of the user who added this organizer
       */
      added_by?: string;
      /**
       * Date and time when organizer was added
       */
      added_at?: string;
    }>;
  };
};

export type GetEventByEventIdOrganizersResponse = GetEventByEventIdOrganizersResponses[keyof GetEventByEventIdOrganizersResponses];

export type GetEventExportByEventIdData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event
     */
    event_id: string;
  };
  query?: never;
  url: '/event/export/{event_id}';
};

export type GetEventExportByEventIdErrors = {
  /**
   * Bad request - Event ID is required
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    success?: boolean;
    message?: string;
  };
  /**
   * Forbidden - Insufficient permissions
   */
  403: {
    success?: boolean;
    message?: unknown;
  };
  /**
   * Event not found - the specified event ID does not exist
   */
  404: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    success?: boolean;
    message?: string;
  };
};

export type GetEventExportByEventIdError = GetEventExportByEventIdErrors[keyof GetEventExportByEventIdErrors];

export type GetEventExportByEventIdResponses = {
  /**
   * Binary Excel file content
   */
  200: Blob | File;
};

export type GetEventExportByEventIdResponse = GetEventExportByEventIdResponses[keyof GetEventExportByEventIdResponses];

export type GetEventAttendanceCountData = {
  body?: never;
  path: {
    /**
     * The unique identifier of the event.
     */
    event_id: string;
  };
  query?: never;
  url: '/event/{event_id}/attendance_count';
};

export type GetEventAttendanceCountErrors = {
  /**
   * Missing event ID parameter.
   */
  400: {
    status?: string;
    message?: string;
  };
  /**
   * Event not found.
   */
  404: {
    status?: string;
    message?: string;
  };
  /**
   * Internal server error.
   */
  500: {
    status?: string;
    message?: string;
  };
};

export type GetEventAttendanceCountError = GetEventAttendanceCountErrors[keyof GetEventAttendanceCountErrors];

export type GetEventAttendanceCountResponses = {
  /**
   * Event attendance count retrieved successfully.
   */
  200: {
    status?: string;
    message?: string;
    data?: {
      /**
       * Total number of attendees who have checked in.
       */
      totalAttendance?: number;
      /**
       * Total number of attendees who have checked out.
       */
      totalCheckedOut?: number;
    };
  };
};

export type GetEventAttendanceCountResponse = GetEventAttendanceCountResponses[keyof GetEventAttendanceCountResponses];

export type PatchEventByEventIdPostData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event to post.
     */
    event_id: string;
  };
  query?: never;
  url: '/event/{event_id}/post';
};

export type PatchEventByEventIdPostErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type PatchEventByEventIdPostResponses = {
  /**
   * Event posted successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: null;
  };
};

export type PatchEventByEventIdPostResponse = PatchEventByEventIdPostResponses[keyof PatchEventByEventIdPostResponses];

export type PatchEventByEventIdDraftData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event to save as draft.
     */
    event_id: string;
  };
  query?: never;
  url: '/event/{event_id}/draft';
};

export type PatchEventByEventIdDraftErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type PatchEventByEventIdDraftResponses = {
  /**
   * Event saved as draft
   */
  200: {
    success?: boolean;
    message?: string;
    data?: null;
  };
};

export type PatchEventByEventIdDraftResponse = PatchEventByEventIdDraftResponses[keyof PatchEventByEventIdDraftResponses];

export type PostEventMassCheckOutByEventIdData = {
  body: {
    /**
     * Array of student IDs to check out.
     */
    student_ids: Array<number>;
    /**
     * Optional checkout time in HH:MM (Philippines time) or ISO 8601 format.
     */
    checkout_time?: string;
  };
  path: {
    /**
     * The unique ID of the event.
     */
    event_id: string;
  };
  query?: never;
  url: '/event/mass_check_out/{event_id}';
};

export type PostEventMassCheckOutByEventIdErrors = {
  /**
   * Bad request — student_ids array is required
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden — Admin/CSG/Organizer only
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type PostEventMassCheckOutByEventIdResponses = {
  /**
   * Mass check-out completed
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      updatedCount?: number;
      /**
       * Student IDs that were already checked out.
       */
      alreadyCheckedOut?: Array<number>;
      /**
       * Student IDs that had not checked in.
       */
      notCheckedIn?: Array<number>;
    };
  };
};

export type PostEventMassCheckOutByEventIdResponse = PostEventMassCheckOutByEventIdResponses[keyof PostEventMassCheckOutByEventIdResponses];

export type PostEventByEventIdCheckinByStudentIdData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event.
     */
    event_id: string;
    /**
     * The numeric student ID to check in.
     */
    student_id: number;
  };
  query?: never;
  url: '/event/{event_id}/checkin/{student_id}';
};

export type PostEventByEventIdCheckinByStudentIdErrors = {
  /**
   * Bad request — capacity reached or already checked in
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden — Admin/CSG/Organizer only, or onboarding not complete
   */
  403: unknown;
  /**
   * Event or student not found
   */
  404: unknown;
  /**
   * Conflict - already checked in
   */
  409: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type PostEventByEventIdCheckinByStudentIdError = PostEventByEventIdCheckinByStudentIdErrors[keyof PostEventByEventIdCheckinByStudentIdErrors];

export type PostEventByEventIdCheckinByStudentIdResponses = {
  /**
   * Student checked in successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      event_id?: string;
      event_name?: string;
      student_id?: number;
      student_name?: string;
      check_in_at?: string;
      check_in_by?: string;
    };
  };
};

export type PostEventByEventIdCheckinByStudentIdResponse = PostEventByEventIdCheckinByStudentIdResponses[keyof PostEventByEventIdCheckinByStudentIdResponses];

export type PostEventByEventIdCheckoutByStudentIdData = {
  body?: never;
  path: {
    /**
     * The unique ID of the event.
     */
    event_id: string;
    /**
     * The numeric student ID to check out.
     */
    student_id: number;
  };
  query?: never;
  url: '/event/{event_id}/checkout/{student_id}';
};

export type PostEventByEventIdCheckoutByStudentIdErrors = {
  /**
   * Bad request — student has not checked in, or event_id / student_id missing
   */
  400: {
    success?: boolean;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden — Admin/CSG/Organizer only, or onboarding not complete
   */
  403: unknown;
  /**
   * Event or student not found
   */
  404: unknown;
  /**
   * Student has already checked out of this event
   */
  409: {
    success?: boolean;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: unknown;
};

export type PostEventByEventIdCheckoutByStudentIdError = PostEventByEventIdCheckoutByStudentIdErrors[keyof PostEventByEventIdCheckoutByStudentIdErrors];

export type PostEventByEventIdCheckoutByStudentIdResponses = {
  /**
   * Student checked out successfully
   */
  200: {
    success?: boolean;
    message?: string;
    data?: {
      event_id?: string;
      event_name?: string;
      student_id?: number;
      student_name?: string;
      checked_out_at?: string;
      checked_out_by?: string;
    };
  };
};

export type PostEventByEventIdCheckoutByStudentIdResponse =
  PostEventByEventIdCheckoutByStudentIdResponses[keyof PostEventByEventIdCheckoutByStudentIdResponses];
